# Generated by Django 4.2.9 on 2024-03-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_notification_periodicallynotification_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="periodicallynotificationshots",
            name="notification",
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"verbose_name": "Xabarnoma ", "verbose_name_plural": "Xabarnomalar "},
        ),
        migrations.AlterModelOptions(
            name="notificationshots",
            options={"verbose_name": "Xabarnoma rasmi", "verbose_name_plural": "Xabarnoma rasmlari "},
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan vaqti"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Yaratildi"), (1, "Bajarildi"), (2, "Jarayonda")], default=0, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="notificationshots",
            name="image",
            field=models.ImageField(upload_to="notification", verbose_name="Rasm"),
        ),
        migrations.DeleteModel(
            name="PeriodicallyNotification",
        ),
        migrations.DeleteModel(
            name="PeriodicallyNotificationShots",
        ),
    ]
