# Generated by Django 4.2.9 on 2024-03-09 12:37

import app.products.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Nomi")),
                ("name_ru", models.CharField(max_length=100, null=True, verbose_name="Nomi")),
                ("name_uz", models.CharField(max_length=100, null=True, verbose_name="Nomi")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=app.products.models.upload_path, verbose_name="Rasmi"
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="Активный?")),
            ],
            options={
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "Kategoriyalar",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Nomi")),
                ("name_ru", models.CharField(max_length=100, null=True, verbose_name="Nomi")),
                ("name_uz", models.CharField(max_length=100, null=True, verbose_name="Nomi")),
                ("price", models.IntegerField(verbose_name="Narxi")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=app.products.models.upload_path, verbose_name="Rasmi"
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="Активный?")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="products", to="products.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Maxsulot",
                "verbose_name_plural": "Maxsulotlar",
            },
        ),
    ]
