# Generated by Django 4.2.9 on 2024-03-12 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0005_branch_tg_id"),
        ("users", "0005_notification_periodicallynotification_and_more"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment", models.TextField(blank=True, null=True)),
                ("cash_type", models.CharField(max_length=10)),
                ("delivery", models.CharField(max_length=3)),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                ("distance", models.CharField(blank=True, max_length=10, null=True)),
                ("cost", models.CharField(max_length=10)),
                ("delivery_cost", models.CharField(max_length=10)),
                ("all_cost", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("created", "Yaratildi"), ("proceed", "Ko'rib chiqildi")],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("filial", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="address.branch")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.telegramuser"
                    ),
                ),
            ],
        ),
    ]
