# Generated by Django 4.2.9 on 2024-03-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="charge_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="cash_type",
            field=models.CharField(choices=[("click", "Click"), ("payme", "Payme")], default="payme", max_length=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("created", "Yaratildi"), ("proceed", "Ko'rib chiqildi"), ("paid", "To'landi")],
                default="created",
                max_length=20,
            ),
        ),
    ]
