# Generated by Django 4.2.9 on 2024-03-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_category_image_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_ru",
            field=models.CharField(max_length=150, null=True, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_uz",
            field=models.CharField(max_length=150, null=True, verbose_name="Nomi"),
        ),
    ]
