# Generated by Django 4.2.9 on 2024-03-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_name_alter_product_name_ru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cost",
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_cost",
            field=models.CharField(default=0, max_length=10),
        ),
    ]
