# Generated by Django 4.2.9 on 2024-03-27 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_order_cost_alter_order_delivery_cost"),
    ]

    operations = [
        migrations.CreateModel(
            name="SelectedProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("count", models.IntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_products",
                        to="products.order",
                    ),
                ),
            ],
        ),
    ]
