# Generated by Django 4.2.9 on 2024-03-11 00:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("long", models.FloatField()),
                ("lat", models.FloatField()),
            ],
            options={
                "verbose_name": "Manzil",
                "verbose_name_plural": "Manzillar",
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", ckeditor.fields.RichTextField(blank=True, max_length=1023, null=True)),
                ("long", models.FloatField()),
                ("lat", models.FloatField()),
                ("is_active", models.BooleanField(default=False, verbose_name="Faolmi?")),
            ],
            options={
                "verbose_name": "Filial",
                "verbose_name_plural": "Filiallar",
            },
        ),
    ]
