# Generated by Django 4.2.9 on 2024-03-11 00:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="description_ru",
            field=ckeditor.fields.RichTextField(blank=True, max_length=1023, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="description_uz",
            field=ckeditor.fields.RichTextField(blank=True, max_length=1023, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="name_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="name_uz",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
