# Generated by Django 4.2.9 on 2024-03-11 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0002_branch_description_ru_branch_description_uz_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="lat",
            new_name="latitude",
        ),
        migrations.RenameField(
            model_name="address",
            old_name="long",
            new_name="longitude",
        ),
        migrations.RenameField(
            model_name="branch",
            old_name="lat",
            new_name="latitude",
        ),
        migrations.RenameField(
            model_name="branch",
            old_name="long",
            new_name="longitude",
        ),
    ]
