# Generated by Django 4.2.9 on 2024-03-11 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_notification_periodicallynotification_and_more"),
        ("address", "0003_rename_lat_address_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, related_name="address", to="users.telegramuser"
            ),
            preserve_default=False,
        ),
    ]
