# Generated by Django 4.2.9 on 2024-03-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0004_address_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="tg_id",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Telegram gruppa ID"),
        ),
    ]
